#ifndef __TOURNAMENT_H__
#define __TOURNAMENT_H__

#include "group.h"

#define QUALIFYING_STAGE_GROUP_COUNT 9
#define QUALIFYING_STAGE_GROUP_TEAM_COUNT 6
#define GROUP_TEAM_COUNT 4
#define GROUP_COUNT 6
#define QUALIFICATION_MATCH_COUNT 260
#define QUALIFIED_TEAM_COUNT 24
#define PLAYOFF_TEAM_COUNT 8
#define PLAYOFF_POT_COUNT 2
#define KNOCKOUT_PHASE_TEAM_COUNT 16
#define QUARTER_FINAL_TEAM_COUNT 8
#define SEMI_FINAL_TEAM_COUNT 4
#define FINAL_TEAM_COUNT 2

void tournament();

#endif
